// <auto-generated />
using System;
using System.Text.Json;
using Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250227151048_meeting_documents")]
    partial class meeting_documents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Types.CustomModels.CustomModelDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AwsModelStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aws_model_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataAccessRoleArn")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("data_access_role_arn");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("language_code");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("modelname");

                    b.Property<string>("ModelSetupMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("model_setup_status");

                    b.Property<int?>("ModelSetupProgress")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("model_setup_progress");

                    b.Property<string>("PreSignedUrl")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("presigned_url");

                    b.Property<DateTime?>("PreSignedUrlExpire")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("presigned_url_expire");

                    b.Property<string>("StateMachineExecutionArn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("state_machine_execution_arn");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrainingDataS3Uri")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("training_data_s3_uri");

                    b.Property<string>("TrainingDataS3UriFolder")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("training_data_s3_uri_folder");

                    b.Property<int?>("TranscribeBaseModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("transcribe_base_model_name");

                    b.Property<string>("TranscribedDataS3Uri")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("transcribed_data_s3_uri");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("custom_models", (string)null);
                });

            modelBuilder.Entity("Common.Types.CustomVocabularies.CustomVocabularyDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_step");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("language_code");

                    b.Property<string>("PublishError")
                        .HasColumnType("text")
                        .HasColumnName("publish_error");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VocabularyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("vocabulary_name");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("custom_vocabularies", (string)null);
                });

            modelBuilder.Entity("Common.Types.MeetingDocuments.MeetingDocumentDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("filename");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("TeamId");

                    b.ToTable("meeting_documents", (string)null);
                });

            modelBuilder.Entity("Common.Types.MeetingPromptResponses.MeetingPromptResponseDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("MeetingId");

                    b.Property<Guid?>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_response");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("TeamId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("PromptId");

                    b.HasIndex("TeamId");

                    b.ToTable("meeting_prompt_responses", (string)null);
                });

            modelBuilder.Entity("Common.Types.Meetings.MeetingDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_step");

                    b.Property<Guid?>("CustomModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_model_id");

                    b.Property<Guid?>("CustomVocabularyId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_vocabulary_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meeting_date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IncludeInModelTraining")
                        .HasColumnType("boolean");

                    b.Property<JsonDocument>("MeetingAnalyticsPayload")
                        .HasColumnType("jsonb");

                    b.Property<string>("MeetingNotes")
                        .HasColumnType("text")
                        .HasColumnName("meeting_notes");

                    b.Property<int?>("MeetingNotesVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("meeting_notes_version");

                    b.Property<string>("PreSignedUrl")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("pre_signe_url");

                    b.Property<Guid?>("PromptSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("S3OutputBucketName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("s3_output_bucket_name");

                    b.Property<string>("S3OutputKeyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("s3_output_key_name");

                    b.Property<string>("S3RecordingFullPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("s3_recording_full_path");

                    b.Property<string>("S3TranscribedFullPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("s3_transcribed_fullpath");

                    b.Property<string>("StateMachineExecutionArn")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("state_machine_execution_arn");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("TranscribeError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("transcribe_error");

                    b.Property<string>("TranscribedPreSignedUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomModelId");

                    b.HasIndex("CustomVocabularyId");

                    b.HasIndex("PromptSetId");

                    b.HasIndex("TeamId");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("Common.Types.PromptSets.PromptSetDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BedrockModelId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bedrock_model_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("PromptSetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_set_name");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("promptsets", (string)null);
                });

            modelBuilder.Entity("Common.Types.Prompts.PromptDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid?>("MeetingPromptResponseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("order");

                    b.Property<Guid>("PrompSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_set_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("prompt");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PrompSetId");

                    b.HasIndex("TeamId");

                    b.ToTable("prompts", (string)null);
                });

            modelBuilder.Entity("Common.Types.Teams.TeamDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdpGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idp_group");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Common.Types.VocabularyPhrases.VocabularyPhraseDatabaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomVocabularyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayAs")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_as");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("vocabulary_name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomVocabularyId");

                    b.HasIndex("TeamId");

                    b.ToTable("vocabulary_phrases", (string)null);
                });

            modelBuilder.Entity("Common.Types.CustomModels.CustomModelDatabaseType", b =>
                {
                    b.HasOne("Common.Types.Teams.TeamDatabaseType", "Team")
                        .WithMany("CustomModels")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Common.Types.CustomVocabularies.CustomVocabularyDatabaseType", b =>
                {
                    b.HasOne("Common.Types.Teams.TeamDatabaseType", "Team")
                        .WithMany("CustomVocabularies")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Common.Types.MeetingDocuments.MeetingDocumentDatabaseType", b =>
                {
                    b.HasOne("Common.Types.Meetings.MeetingDatabaseType", "Meeting")
                        .WithMany("MeetingDocuments")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Types.Teams.TeamDatabaseType", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Common.Types.MeetingPromptResponses.MeetingPromptResponseDatabaseType", b =>
                {
                    b.HasOne("Common.Types.Meetings.MeetingDatabaseType", "Meeting")
                        .WithMany("MeetingPromptResponses")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Types.Prompts.PromptDatabaseType", "Prompt")
                        .WithMany("MeetingPromptResponses")
                        .HasForeignKey("PromptId");

                    b.HasOne("Common.Types.Teams.TeamDatabaseType", "Team")
                        .WithMany("MeetingPromptResponses")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Prompt");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Common.Types.Meetings.MeetingDatabaseType", b =>
                {
                    b.HasOne("Common.Types.CustomModels.CustomModelDatabaseType", "CustomModel")
                        .WithMany("Meetings")
                        .HasForeignKey("CustomModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Common.Types.CustomVocabularies.CustomVocabularyDatabaseType", "CustomVocabulary")
                        .WithMany("Meetings")
                        .HasForeignKey("CustomVocabularyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Common.Types.PromptSets.PromptSetDatabaseType", "PromptSet")
                        .WithMany("Meetings")
                        .HasForeignKey("PromptSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Common.Types.Teams.TeamDatabaseType", "Team")
                        .WithMany("Meetings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomModel");

                    b.Navigation("CustomVocabulary");

                    b.Navigation("PromptSet");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Common.Types.PromptSets.PromptSetDatabaseType", b =>
                {
                    b.HasOne("Common.Types.Teams.TeamDatabaseType", "Team")
                        .WithMany("PromptSets")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Common.Types.Prompts.PromptDatabaseType", b =>
                {
                    b.HasOne("Common.Types.PromptSets.PromptSetDatabaseType", "PromptSet")
                        .WithMany("Prompts")
                        .HasForeignKey("PrompSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Types.Teams.TeamDatabaseType", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("PromptSet");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Common.Types.VocabularyPhrases.VocabularyPhraseDatabaseType", b =>
                {
                    b.HasOne("Common.Types.CustomVocabularies.CustomVocabularyDatabaseType", "CustomVocabulary")
                        .WithMany("Phrases")
                        .HasForeignKey("CustomVocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Types.Teams.TeamDatabaseType", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomVocabulary");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Common.Types.CustomModels.CustomModelDatabaseType", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("Common.Types.CustomVocabularies.CustomVocabularyDatabaseType", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("Phrases");
                });

            modelBuilder.Entity("Common.Types.Meetings.MeetingDatabaseType", b =>
                {
                    b.Navigation("MeetingDocuments");

                    b.Navigation("MeetingPromptResponses");
                });

            modelBuilder.Entity("Common.Types.PromptSets.PromptSetDatabaseType", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("Common.Types.Prompts.PromptDatabaseType", b =>
                {
                    b.Navigation("MeetingPromptResponses");
                });

            modelBuilder.Entity("Common.Types.Teams.TeamDatabaseType", b =>
                {
                    b.Navigation("CustomModels");

                    b.Navigation("CustomVocabularies");

                    b.Navigation("MeetingPromptResponses");

                    b.Navigation("Meetings");

                    b.Navigation("PromptSets");
                });
#pragma warning restore 612, 618
        }
    }
}
